apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  SERVER_DISCOVERY: {{ .Values.configMap.data.SERVER_DISCOVERY | quote }}

  # Replace these placeholders with the values currently used in your .env file.
  SECURITY_ENABLED: {{ .Values.configMap.data.SECURITY_ENABLED | quote }}
  CACHE_ENABLED: {{ .Values.configMap.data.CACHE_ENABLED | quote }}
  CACHE_PROVIDER: {{ .Values.configMap.data.CACHE_PROVIDER | quote }}
  EUREKA_INSTANCE_HOSTNAME: {{ .Values.configMap.data.EUREKA_INSTANCE_HOSTNAME | quote }}
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: {{ .Values.configMap.data.EUREKA_INSTANCE_PREFER_IP_ADDRESS | quote }}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_FILTERCHAINPROXY: {{ .Values.configMap.data.LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_FILTERCHAINPROXY | quote }}