apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }} 
    kind: SecretStore

  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner

  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecrets.authentication.key | quote }}
        property: {{ .Values.externalSecret.remoteSecrets.authentication.properties.jwtSecret | quote }}