apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }} 
    kind: SecretStore

  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner

  data:
    - secretKey: DATASOURCE_URL
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecrets.database.key | quote }}
        property: {{ .Values.externalSecret.remoteSecrets.database.properties.url | quote }}

    - secretKey: DATASOURCE_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecrets.database.key | quote }}
        property: {{ .Values.externalSecret.remoteSecrets.database.properties.username | quote }}

    - secretKey: DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecrets.database.key | quote }}
        property: {{ .Values.externalSecret.remoteSecrets.database.properties.password | quote }}
    
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecrets.authentication.key | quote }}
        property: {{ .Values.externalSecret.remoteSecrets.authentication.properties.jwtSecret | quote }}