application:
  name: service-discovery

service:
  type: LoadBalancer
  port: 8761
  targetPort: 8761

replicaCount: 1

image:
  repository: erickperez091/dev-server-discovery
  tag: 1.0.2
  pullPolicy: Always # Possible values: Always, IfNotPresent, Never

configMap:
  name: config-discovery
  data:
    LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_FILTERCHAINPROXY: "INFO"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  path: /actuator/health/liveness
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  path: /actuator/health/readiness
  initialDelaySeconds: 30
  periodSeconds: 10